[tox]
skipsdist = true
skip_missing_interpreters = true
envlist = lint, unit
requires = tox>=4.21, tox-uv
no_package = true

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/src/:{toxinidir}/reactive/:{toxinidir}/hooks/:{toxinidir}/lib/:{toxinidir}/actions:{toxinidir}/files/:{toxinidir}/files/plugins/
    # avoid state written to file during tests - see https://github.com/juju/charm-helpers/blob/85dcbeaf63b0d0f38e8cb17825985460dc2cd02d/charmhelpers/core/unitdata.py#L179-L184
    UNIT_STATE_DB = :memory:
    # Default to juju 3, but don't overwrite it if already set in the environment.
    # This allows us to still test with juju2.9 for some projects by updating the env externally.
    TEST_JUJU3 = {env:TEST_JUJU3:1}
passenv = *

[testenv:lint]
dependency_groups = lint
commands =
    # Workaround for https://github.com/tox-dev/tox-uv/issues/209
    # `tox-uv<1.16.0` does not recognize `dependency_groups` in Python 3.8
    uv sync --group lint
    ruff check {toxinidir}
    ruff format --check --diff {toxinidir}
    codespell {toxinidir} -I {toxinidir}/.codespell-ignore-words.txt
    mypy {toxinidir}

[testenv:reformat]
dependency_groups = reformat
commands =
    # Workaround for https://github.com/tox-dev/tox-uv/issues/209
    # `tox-uv<1.16.0` does not recognize `dependency_groups` in Python 3.8
    uv sync --group lint
    ruff check --fix {toxinidir}
    ruff format {toxinidir}

[testenv:unit]
setenv =
    {[testenv]setenv}
    COVERAGE_FILE = .coverage-unit
dependency_groups = unit
commands =
    # Workaround for https://github.com/tox-dev/tox-uv/issues/209
    # `tox-uv<1.16.0` does not recognize `dependency_groups` in Python 3.8
    uv sync --group unit
    pytest {toxinidir}/tests/unit \
        -v \
        --cov \
        --cov-report=term-missing \
        --cov-report=html \
        --cov-report=xml \
        {posargs}

[testenv:func]
setenv =
    {[testenv]setenv}
    COVERAGE_FILE = .coverage-func
dependency_groups = func
commands =
    # Workaround for https://github.com/tox-dev/tox-uv/issues/209
    # `tox-uv<1.16.0` does not recognize `dependency_groups` in Python 3.8
    uv sync --group func
    pytest {toxinidir}/tests/functional \
        -v \
        --cov \
        --cov-report=term-missing \
        --cov-report=html \
        --cov-report=xml \
        --cov-fail-under=0 \
        {posargs}

[testenv:integration]
dependency_groups = integration
commands =
    # Workaround for https://github.com/tox-dev/tox-uv/issues/209
    # `tox-uv<1.16.0` does not recognize `dependency_groups` in Python 3.8
    uv sync --group integration
    pytest {toxinidir}/tests/integration \
        -v \
        --tb native \
        --log-cli-level=INFO \
        -s \
        {posargs}
