{
 "title": "SMART Dashboard",
 "description": "Dashboard for monitoring SMART metrics.",
 "tags": [ "smartctl" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(smartctl_version, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "title": "Devices count",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_devices{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Exit status",
   "type": "stat",
   "gridPos": { "x": 3, "y": 1, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(smartctl_device_smartctl_exit_status{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Error log entries",
   "type": "stat",
   "gridPos": { "x": 6, "y": 1, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_num_err_log_entries{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Media errors",
   "type": "stat",
   "gridPos": { "x": 9, "y": 1, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_media_errors{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "SMART error log count",
   "type": "stat",
   "gridPos": { "x": 12, "y": 1, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_error_log_count{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Critical warnings",
   "type": "stat",
   "gridPos": { "x": 15, "y": 1, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device_critical_warning{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "SMART failed",
   "type": "stat",
   "gridPos": { "x": 18, "y": 1, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(1 - smartctl_device_smart_status{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Device Info",
   "type": "table",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "smartctl_device{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SMART overview",
   "type": "table",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(smartctl_device{instance=~\"$instance\"}) by (instance, device, model_name)"
    },
    {
     "expr": "sum(smartctl_device_temperature{instance=~\"$instance\", temperature_type=\"current\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_smartctl_exit_status{instance=~\"$instance\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_smart_status{instance=~\"$instance\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_power_on_seconds{instance=~\"$instance\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_power_cycle_count{instance=~\"$instance\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_interface_speed{instance=~\"$instance\", speed_type=\"current\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_capacity_bytes{instance=~\"$instance\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_capacity_blocks{instance=~\"$instance\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_block_size{blocks_type=\"logical\", instance=~\"$instance\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_block_size{blocks_type=\"physical\", instance=~\"$instance\"}) by (instance, device)"
    },
    {
     "expr": "sum(smartctl_device_error_log_count{instance=~\"$instance\"}) by (instance, device)"
    }
   ]
  },
  {
   "title": "SMART attributes",
   "type": "table",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "x": 0, "y": 28, "w": 24, "h": 1 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 29, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_temperature{instance=~\"$instance\",temperature_type=\"current\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Smartctl exit status",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 29, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_smartctl_exit_status{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "SMART passed",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 29, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_smart_status{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Power on 1 hour",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 29, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (model_name) (increase(smartctl_device_power_on_seconds{instance=~\"$instance\"}[1h]) * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Power cycle count",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 37, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_power_cycle_count{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Write percentage used",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 37, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_percentage_used{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "NVMe capacity bytes",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 37, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_nvme_capacity_bytes{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Number of error log entries",
   "type": "timeseries",
   "description": "Contains the number of Error Information log entries over the life of the controller",
   "gridPos": { "x": 18, "y": 37, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_num_err_log_entries{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Number of media errors",
   "type": "timeseries",
   "description": "Contains the number of occurrences where the controller detected an unrecovered data integrity error. Errors such as uncorrectable ECC, CRC checksum failure, or LBA tag mismatch are included in this field",
   "gridPos": { "x": 0, "y": 45, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_media_errors{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "SMART error log count",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 45, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_error_log_count{instance=~\"$instance\",error_log_type=\"summary\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Critical warnings for state of controller",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 45, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_critical_warning{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Interface speed (current)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 53, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_interface_speed{instance=~\"$instance\",speed_type=\"current\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Interface speed (max)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 53, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_interface_speed{instance=~\"$instance\",speed_type=\"max\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Capacity Bytes",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 61, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_capacity_bytes{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Capacity Blocks",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 61, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_capacity_blocks{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Bytes written",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 61, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_bytes_written{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Bytes read",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 61, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_bytes_read{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Block size (logical)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 69, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_block_size{instance=~\"$instance\",blocks_type=\"logical\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Block size (physical)",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 69, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_block_size{instance=~\"$instance\",blocks_type=\"physical\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Available spare threshold",
   "type": "timeseries",
   "description": "When the Available Spare falls below the threshold indicated in this field, an asynchronous event completion may occur. The value is indicated as a normalized percentage (0 to 100%)",
   "gridPos": { "x": 12, "y": 69, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_available_spare_threshold{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  {
   "title": "Available spare",
   "type": "timeseries",
   "description": "Normalized percentage (0 to 100%) of the remaining spare capacity available",
   "gridPos": { "x": 18, "y": 69, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (model_name) (smartctl_device_available_spare{instance=~\"$instance\"} * on(device, juju_unit) group_left(model_name) smartctl_device{instance=~\"$instance\"})",
     "legendFormat": "{{ model_name }}"
    }
   ]
  },
  { "title": "Go Runtime Metrics", "type": "row", "gridPos": { "x": 0, "y": 77, "w": 24, "h": 1 } },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 78, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (process_open_fds{instance=~\"$instance\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 4, "y": 78, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 78, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(process_resident_memory_bytes{instance=~\"$instance\"}[1h]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Stack Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 78, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_stack_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "sys"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{instance=~\"$instance\"})",
     "legendFormat": "inuse"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 78, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_sys_bytes{instance=~\"$instance\"})",
     "legendFormat": "sys"
    },
    {
     "expr": "avg(go_memstats_heap_idle_bytes{instance=~\"$instance\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "avg(go_memstats_heap_released_bytes{instance=~\"$instance\"})",
     "legendFormat": "released"
    },
    {
     "expr": "avg(go_memstats_next_gc_bytes{instance=~\"$instance\"})",
     "legendFormat": "next_gc"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{instance=~\"$instance\"})",
     "legendFormat": "inuse"
    },
    {
     "expr": "avg(go_memstats_heap_alloc_bytes{instance=~\"$instance\"})",
     "legendFormat": "alloc"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "x": 20, "y": 78, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod) (go_memstats_heap_objects{instance=~\"$instance\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 86, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (go_threads{instance=~\"$instance\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "x": 4, "y": 86, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutines{instance=~\"$instance\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Go Alloc Rate",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 86, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_memstats_alloc_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Go Alloc Bytes",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 86, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (go_memstats_alloc_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Go GC Per Second",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 86, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_gc_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Go GC Duration Seconds",
   "type": "timeseries",
   "gridPos": { "x": 20, "y": 86, "w": 4, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_gc_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}