# The alerts use DCGM_FI_DEV_CLOCK_THROTTLE_REASONS metric to detect throttling events on NVIDIA GPUs,
# which is a bitmask of throttle reasons found here: https://docs.nvidia.com/datacenter/dcgm/2.1/dcgm-api/group__dcgmFieldConstants.html.
# The 8 least significant bits are used for the alerts, with each bit representing a different throttle reason.

groups:
- name: NVIDIA DCGM Throttling Alerts
  rules:
    - alert: GPUPowerBrakeThrottle
      # isolate the least significant 8 bits with % 256
      # check whether bit 7 (starts from bit 0) has been set with the >= bool 128 comparison
      expr: DCGM_FI_DEV_CLOCK_THROTTLE_REASONS % 256 >= 128
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU Hardware Power Brake Slowdown throttling detected. (instance {{ $labels.Hostname }})
        description: |
          HW Power Brake Slowdown (reducing the core clocks by a factor of 2 or more) is engaged on NVIDIA GPU: {{ $labels.gpu }}
          This is an indicator of: 
              - External Power Brake Assertion being triggered (e.g. by the system power supply)
            LABELS = {{ $labels }}
    - alert: GPUThermalHWThrottle
      # isolate the least significant 7 bits with % 128
      # check whether bit 6 (starts from bit 0) has been set with the >= bool 64 comparison
      expr: DCGM_FI_DEV_CLOCK_THROTTLE_REASONS % 128 >= 64
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU Hardware Thermal throttling detected. (instance {{ $labels.Hostname }})
        description: |
          HW Thermal Slowdown (reducing the core clocks by a factor of 2 or more) is engaged on NVIDIA GPU: {{ $labels.gpu }}
          This is an indicator of:
              - Temperature being too high
            LABELS = {{ $labels }}
    - alert: GPUThermalSWThrottle
      # isolate the least significant 6 bits with % 64
      # check whether bit 5 (starts from bit 0) has been set with the >= bool 32 comparison
      expr: DCGM_FI_DEV_CLOCK_THROTTLE_REASONS % 64 >= 32
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU Software Thermal throttling detected. (instance {{ $labels.Hostname }})
        description: |
          SW Thermal Slowdown is engaged on NVIDIA GPU: {{ $labels.gpu }}
          This is an indicator of:
              - Current GPU temperature above the GPU Max Operating Temperature
              - Current memory temperature above the Memory Max Operating Temperature
            LABELS = {{ $labels }}
    - alert: GPUSyncBoostThrottle
      # isolate the least significant 5 bits with % 32
      # check whether bit 4 (starts from bit 0) has been set with the >= bool 16 comparison
      expr: DCGM_FI_DEV_CLOCK_THROTTLE_REASONS % 32 >= 16
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU Sync Boost throttling detected. (instance {{ $labels.Hostname }})
        description: |
          This NVIDIA GPU: {{ $labels.gpu }} has been added to a Sync boost group with nvidia-smi or DCGM in order to maximize performance per watt.
          All GPUs in the sync boost group will boost to the minimum possible clocks across the entire group.
          Look at the throttle reasons for other GPUs in the system to see why those GPUs are holding this one at lower clocks.
            LABELS = {{ $labels }}
    - alert: GPUSlowdownThrottle
      # isolate the least significant 4 bits with % 16
      # check whether bit 3 (starts from bit 0) has been set with the >= bool 8 comparison
      expr: DCGM_FI_DEV_CLOCK_THROTTLE_REASONS % 16 >= 8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU Hardware Slowdown throttling detected. (instance {{ $labels.Hostname }})
        description: |
          HW Slowdown (reducing the core clocks by a factor of 2 or more) is engaged on NVIDIA GPU: {{ $labels.gpu }}
          This is an indicator of:
              - Temperature being too high
              - External Power Brake Assertion is triggered (e.g. by the system power supply)
              - Power draw is too high and Fast Trigger protection is reducing the clocks
              - May be also reported during PState or clock change
            LABELS = {{ $labels }}
    - alert: GPUPowerThrottle
      # isolate the least significant 3 bits with % 8
      # check whether bit 2 (starts from bit 0) has been set with the >= bool 4 comparison
      expr: DCGM_FI_DEV_CLOCK_THROTTLE_REASONS % 8 >= 4
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: GPU Software Power throttling detected. (instance {{ $labels.Hostname }})
        description: |
          SW Power Scaling algorithm is reducing the clocks below requested clocks on NVIDIA GPU: {{ $labels.gpu }}
            LABELS = {{ $labels }}
