groups:
- name: IpmiDcmi
  rules:
    - alert: IPMIDCMICommandSuccessMetricsMissing
      expr: absent_over_time(ipmi_dcmi_command_success[5m])
      labels:
        severity: critical
      annotations:
        summary: IPMI DCMI command success metrics missing. (instance {{ $labels.instance }})
        description: |
          The ipmi_dcmi_command_success metric has been missing for over 5 minutes.
          This may indicate IPMI DCMI command timeouts, or that IPMI tools/services are not installed or supported on this hardware.
            LABELS = {{ $labels }}

    - alert: IPMIDCMICommandFailed
      expr: ipmi_dcmi_command_success == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Failed to run ipmi_dcmi. (instance {{ $labels.instance }})
        description: |
          Failed to get system power statistics using ipmi_dcmi.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}

    - alert: IPMIDCMIPowerConsumptionPercentageOutstanding
      expr: ipmi_dcmi_power_consumption_percentage >= 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: IPMI DCMI power consumption percentage is high. (instance {{ $labels.instance }})
        description: |
          IPMI DCMI power consumption percentage is high for over 5 minutes.
            POWER_CONSUMPTION_PERCENTAGE = {{ $value }}
            LABELS = {{ $labels }}
