groups:
- name: IpmiSel
  rules:
    - alert: IPMISELCommandSuccessMetricsMissing
      expr: absent_over_time(ipmi_sel_command_success[5m])
      labels:
        severity: critical
      annotations:
        summary: IPMI SEL command success metrics missing. (instance {{ $labels.instance }})
        description: |
          The ipmi_sel_command_success metric has been missing for over 5 minutes.
          This may indicate IPMI SEL command timeouts, or that IPMI tools/services are not installed or supported on this hardware.
            LABELS = {{ $labels }}

    - alert: IPMISELCommandFailed
      expr: ipmi_sel_command_success == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Failed to run ipmi-sel. (instance {{ $labels.instance }})
        description: |
          Failed to get system event logs using ipmi-sel.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}

    - alert: IPMISELStateWarning
      expr: ipmi_sel_state_warning > 0
      labels:
        severity: warning
        event_id: '{{ $value }}'
      annotations:
        summary: IPMI system event log in warning state. (instance {{ $labels.instance }})
        description: |
          IPMI SEL entry in warning state.
            LABELS = {{ $labels }}
            EVENT_ID = {{ $value }}

    - alert: IPMISELStateCritical
      expr: ipmi_sel_state_critical > 0
      labels:
        severity: critical
        event_id: '{{ $value }}'
      annotations:
        summary: IPMI system event log in critical state. (instance {{ $labels.instance }})
        description: |
          IPMI SEL entry in critical state.
            LABELS = {{ $labels }}
            EVENT_ID = {{ $value }}

    - alert: IPMISELDStateWarning
      expr: node_systemd_unit_state{name="ipmiseld.service", state=~"failed|inactive"} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: IPMISELD service is not active. (instance {{ $labels.instance }})
        description: |
          The ipmiseld service is not active, indicating a potential problem.
            VALUE = {{ $value }}
            LABELS = {{ $labels }}
