groups:
- name: SMART
  rules:

  - alert: SmartDriveReliabilityDegraded
    expr: smartctl_device_critical_warning == 4
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: SMART alert for critical warning attribute on an NVMe controller due to degradation in drive reliability. (instance {{ $labels.instance }})
      description: |
        Drive reliability is degraded. Bit 02 of critical warning SMART attribute is set.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartDriveinReadOnlyMode
    expr: smartctl_device_critical_warning == 8
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: SMART alert for critical warning attribute on an NVMe controller due to drive being in read-only mode. (instance {{ $labels.instance }})
      description: |
        Drive is in read-only mode. Bit 03 of critical warning SMART attribute is set.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartHealthStatusFail
    expr: smartctl_device_smart_status == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: SMART health status failed for device. (instance {{ $labels.instance }})
      description: |
        SMART health status failed for device. This means either that the device has already failed, or that it is predicting its own failure within the next 24 hours.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartExitStatusDiskFail
    expr: smartctl_device_smartctl_exit_status == 8
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: smartctl exit status returned "DISK FAILING". (instance {{ $labels.instance }})
      description: |
        smartctl exit status returned "DISK FAILING". Bit 3 of smartctl exit status is set.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartExitStatusPrefailBelowThreshold
    expr: smartctl_device_smartctl_exit_status == 16
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: smartctl exit status reports pre-fail attribute for device is below threshold. (instance {{ $labels.instance }})
      description: |
        smartctl exit status pre-fail attribute is below threshold. Bit 4 of smartctl exit status is set.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartNvmeWearoutIndicator
    expr: smartctl_device_available_spare{device=~"nvme.*"} < smartctl_device_available_spare_threshold{device=~"nvme.*"}
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: SMART alert for available spare space below threshold for NVMe device. (instance {{ $labels.instance }})
      description: |
        Available spare space below threshold for NVMe device.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartDeviceTemperatureCritical
    expr: smartctl_device_temperature > 80
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: SMART alert for critical device temperature. (instance {{ $labels.instance }})
      description: |
        Device temperature is critical.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartAttributeWarning
    expr: smartctl_device_attribute{attribute_id=~"5|187|188|197|198"} > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: SMART device attribute correlating with drive failure has its raw value greater than zero. (instance {{ $labels.instance }})
      description: |
        SMART raw value for attribute "{{ $labels.attribute_name }}" with id "{{ $labels.attribute_id }}"
        on device "{{ $labels.device }}" is greater than 0.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}
