groups:
- name: SMART
  rules:

  - alert: SmartctlCriticalWarning
    expr: smartctl_device_critical_warning > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: SMARTCTL critical warning. (instance {{ $labels.instance }})
      description: |
        Critical warnings present for the state of the controller.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartctlDeviceSmartStatusFail
    expr: smartctl_device_smart_status == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: SMART status for device is 0. (instance {{ $labels.instance }})
      description: |
        SMART status for a device is 0.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}

  - alert: SmartctlExitStatusFail
    expr: smartctl_device_smartctl_exit_status != 0
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: SMARTCTL exit status is bad. (instance {{ $labels.instance }})
      description: |
        SMARTCTL exit status for a device is not 0.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}
