{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.19+) cluster",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
   },
   {
    "name": "gpu",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, gpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "NVIDIA GPU {{gpu}}"
    },
    {
     "expr": "label_replace(\n  node_hwmon_temp_celsius * on(chip) group_left(chip_name) node_hwmon_chip_names{chip_name=\"amdgpu\"}, \n  \"gpu_number\", \"$1\", \"chip_name\", \"(.*)\"\n)\n",
     "legendFormat": "GPU: {{gpu_number}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$gpu\"})",
     "legendFormat": "NVDIA GPUs"
    },
    {
     "expr": "node_hwmon_temp_celsius * on(chip) group_left() node_hwmon_chip_names{chip_name=\"amdgpu\"}",
     "legendFormat": "AMD GPUs"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "label_replace(\n  node_hwmon_power_watt * on(chip) group_left(chip_name) node_hwmon_chip_names{chip_name=\"amdgpu\"}, \n  \"gpu_number\", \"$1\", \"chip_name\", \"(.*)\"\n)",
     "legendFormat": "GPU: {{gpu_number}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$gpu\"})",
     "legendFormat": "NVIDIA GPUs"
    },
    {
     "expr": "sum((node_hwmon_power_watt) * on(chip) node_hwmon_chip_names{chip_name=\"amdgpu\"})",
     "legendFormat": "AMD GPUs"
    },
    { "expression": "($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"$instance\", gpu=~\"$gpu\"} * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}