{
 "title": "GPU Dashboard",
 "description": "Dashboard to monitor NVIDIA and AMD GPU metrics using DCGM and node exporter",
 "tags": [ "gpu" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_hwmon_chip_names,instance)"
    }
   },
   {
    "name": "nvidia_gpu",
    "label": "NVIDIA GPU",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, gpu)"
   },
   {
    "name": "amd_gpu",
    "label": "AMD GPU",
    "query": {
     "query": "label_values(node_drm_card_info,chip)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$nvidia_gpu\"}",
     "legendFormat": "NVIDIA GPU: {{gpu}}"
    },
    {
     "expr": "label_replace(node_hwmon_temp_celsius{instance=~\"$instance\", chip=~\"$amd_gpu\"} * on(chip) group_right() node_drm_card_info{chip=~\"$amd_gpu\"}, \"gpu\", \"$1\", \"card\", \"card([0-9]+)\")\n",
     "legendFormat": "AMD GPU: {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance\", gpu=~\"$nvidia_gpu\"})",
     "legendFormat": "NVDIA GPUs"
    },
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=~\"$instance\", chip=~\"$amd_gpu\"})",
     "legendFormat": "AMD GPUs"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$nvidia_gpu\"}",
     "legendFormat": "NVIDIA GPU: {{gpu}}"
    },
    {
     "expr": "label_replace(node_hwmon_power_average_watt{instance=~\"$instance\", chip=~\"$amd_gpu\"} * on(chip) group_right() node_drm_card_info{chip=~\"$amd_gpu\"}, \"gpu\", \"$1\", \"card\", \"card([0-9]+)\")",
     "legendFormat": "AMD GPU: {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Total Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance\", gpu=~\"$nvidia_gpu\"})",
     "legendFormat": "NVIDIA GPUs"
    },
    {
     "expr": "sum(node_hwmon_power_average_watt{instance=~\"$instance\", chip=~\"$amd_gpu\"})",
     "legendFormat": "AMD GPUs"
    },
    { "expression": "($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance\", gpu=~\"$nvidia_gpu\"}",
     "legendFormat": "NVIDIA GPU: {{gpu}}"
    },
    {
     "expr": "label_replace(node_drm_gpu_busy_percent{instance=~\"$instance\"} * on(card) group_right() node_drm_card_info{chip=~\"$amd_gpu\"}, \"gpu\", \"$1\", \"card\", \"card([0-9]+)\")\n",
     "legendFormat": "AMD GPU: {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FAN_SPEED{instance=~\"$instance\", gpu=~\"$nvidia_gpu\"}",
     "legendFormat": "NVIDIA GPU: {{gpu}}"
    },
    {
     "expr": "label_replace(\n  (\n    node_hwmon_fan_rpm{instance=~\"$instance\", chip=~\"$amd_gpu\"} * on(chip) group_right() node_drm_card_info{chip=~\"$amd_gpu\"}\n  ) /\n  (\n    node_hwmon_fan_max_rpm{instance=~\"$instance\", chip=~\"$amd_gpu\"} * on(chip) group_right() node_drm_card_info{chip=~\"$amd_gpu\"}\n  ) * 100,\n  \"gpu\", \"$1\", \"card\", \"card([0-9]+)\"\n)",
     "legendFormat": "AMD GPU: {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{instance=~\"$instance\", gpu=~\"$nvidia_gpu\"} * 1000000",
     "legendFormat": "NVIDIA GPU: {{gpu}}"
    },
    {
     "expr": "label_replace(node_hwmon_freq_freq_mhz{instance=~\"$instance\", chip=~\"$amd_gpu\", sensor=\"sclk\"} * on(chip) group_right() node_drm_card_info{chip=~\"$amd_gpu\"} * 1000000, \"gpu\", \"$1\", \"card\", \"card([0-9]+)\")",
     "legendFormat": "AMD GPU: {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"$instance\", gpu=~\"$nvidia_gpu\"}",
     "legendFormat": "NVIDIA GPU: {{gpu}}"
    },
    {
     "expr": "label_replace(\n    (\n        node_drm_memory_vram_used_bytes{instance=~\"$instance\"} * on(card) group_right() node_drm_card_info{chip=~\"$amd_gpu\"}\n    ) \n    / \n    (\n        node_drm_memory_vram_size_bytes{instance=~\"$instance\"} * on(card) group_right() node_drm_card_info{chip=~\"$amd_gpu\"}\n    ) * 100,\n    \"gpu\", \"$1\", \"card\", \"card([0-9]+)\"\n)",
     "legendFormat": "AMD GPU: {{gpu}}"
    }
   ]
  }
 ]
}